### ISSUE TITLE
Script install wrong version without programming ligatures

### ISSUE THREAD

**Issue by bentolor** [stevebscott/steves-bash-utils#2]
The script did not work for me: Font did not show any ligatures.

I installed directly the deb https://debian.pkgs.org/9/debian-contrib-i386/fonts-firacode_1.204-2_all.deb.html  (works on older versions, too) and ligatures imemdiately worked

**Comment by stevebscott** [comment]
I just got around to testing this. Installing the deb directly, or through apt, enabled the ligatures.

The deb comes from a different variant of FiraCode; from: https://github.com/tonsky/FiraCode and not from the official FiraSans repository: https://github.com/bBoxType/FiraSans ("Fira Code is Fira Mono 3.206 with less Line Space (1.0) – does not include programming ligatures").
